apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authoring-deployment.yaml
secretGenerator:
  - name: authoring-ssh-keys
    files:
      # Please remember to generate missing files
      - resources/secrets/.ssh/authorized_keys
      - resources/secrets/.ssh/config
      - resources/secrets/.ssh/id_rsa
      - resources/secrets/.ssh/id_rsa.pub
