apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arbiter-deployment.yaml
configMapGenerator:
  - name: arbiter-config
    files:
      - resources/config/hazelcast-config.yaml
